export const EMPLOYEE_REGISTER_REQUEST = 'EMPLOYEE_REGISTER_REQUEST';
export const EMPLOYEE_REGISTER_SUCCESS = 'EMPLOYEE_REGISTER_SUCCESS';
export const EMPLOYEE_REGISTER_FAILURE = 'EMPLOYEE_REGISTER_FAILURE';


export const GET_EMPLOYEE_REQUEST = "GET_EMPLOYEE_REQUEST";
export const GET_EMPLOYEE_SUCCESS = "GET_EMPLOYEE_SUCCESS";
export const GET_EMPLOYEE_FAILURE = "GET_EMPLOYEE_FAILURE";

export const SEARCH_EMPLOYEE = "SEARCH_EMPLOYEE";
export const EMPLOYEE_REGISTER_SUCCESS_MSG_REMOVE = "EMPLOYEE_REGISTER_SUCCESS_MSG_REMOVE";




export const DELETE_EMPLOYEE_REQUEST = 'DELETE_EMPLOYEE_REQUEST';
export const DELETE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS';
export const DELETE_EMPLOYEE_FAILURE = 'DELETE_EMPLOYEE_FAILURE';


export const GET_SINGLE_EMPLOYEE = "GET_SINGLE_EMPLOYEE";
export const GET_SINGLE_EMPLOYEE_SUCCESS = "GET_SINGLE_EMPLOYEE_SUCCESS";
export const GET_SINGLE_EMPLOYEE_FAILURE = "GET_SINGLE_EMPLOYEE_FAILURE";





